### ISSUE TITLE
Implement inhabit subcommand

### ISSUE THREAD

**Issue by RadicalZephyr** [bike-barn/hermit#105]
Switch with hermit shell is currently inhabited.  This means changing the global storage of what the shell's name is as well as removing symlinks to the old shell's files, and creating symlinks to the new shell's files.

**Comment by reillysiemens** [comment]
This is going to cause problems if we try to have modules named after the subcommand since `use` is a keyword in Rust. Trying to compile with a `src/use.rs` module results in something like this
```
src/main.rs:4:5: 4:8 error: expected identifier, found keyword `use`
src/main.rs:4 mod use;
```
We may have to reconsider our naming structure based around this if we want to have a common naming structure for all subcommands.

**Comment by reillysiemens** [comment]
An alternative would be to use a name besides `use`. Something more... crabby... perhaps?

**Comment by houngj** [comment]
Not sure how to make something crabby, but maybe `apply`?

**Comment by reillysiemens** [comment]
Looks like we've settled on `inhabit` as an alternative to `use`. I like it. Some genius probably suggested it.

**Comment by reillysiemens** [comment]
`inhabit`'s argument pattern is `hermit inhabit [shell-name]`. In the case where a `shell-name` is provided `hermit` should inhabit that shell. Where a `shell-name` is not provided `hermit` should not change the current shell and should instead print all available shells to `stdout` in alphabetical order, one-per-line.

For example:
```
[19:11:35] user@host:~ $ hermit inhabit
dev 
home
school
work
```
